# Permalinks
permalink:           pretty

# Setup
title:               Metis Data Science Bootcamp
tagline:             Student First Blog
url:                 http://svikhter.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Slava Vikhter
  url:               https://www.linkedin.com/in/slavavikhter/
  email:             svikhter@tsbcglobal.net

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/svikhter

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
